server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql
      mode: always
app:
  cors:
    allowed-origins-patterns: https://*.cartagenacorporation.com
demo:
  ws:
    consultar-productos-activos:
      endpoint: https://m9381.wiremockapi.cloud/detalles-cuenta
      timeout: 120000
movcli:
  jaxb:
    marshaller:
      packagescan: com.nsbt.demo.model